github_user: greenpeace
github_repository: gpes-climate-chart
markdown: kramdown
title: "Climate chart"
long_title: "Last 10 years"
lead: >
  <p>Making visualisations or interactive content that works in many other sites can be difficult. I hope this tool will help to make it a little easier.</p>
  <p>Here you can develop, test and translate interactive visualisations in different Greenpeace layouts. Use it to test your work in the following example pages:</p>
